name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
